### ISSUE TITLE
Plugin not installed

### ISSUE THREAD

**Issue by rjutras** [valiquette/homebridge-orbit-irrigation#2]
Problem: " orbit bridge start but no plugins installed. 

We have followed the following instructions:
1-  Installed the plugin using: npm install -g homebridge-orbit-irrigation
2- Edited config.json and added my account detail. 
{
	"name": "B-Hyve",
	"email": "xxxx@xxxx.xx",
	"password": "xxxxx",
	"defaultRuntime": 1,
	"useIrrigationDisplay": true,
	"showStandby": true,
	"showRunall": true,
	"showSchedules": true,
	"_bridge": {
		"username": "12:34:5G:6B:78",
		"port": 12345
	},
	"platform": "bhyve"
}
3- Tried to add in homekit but no plugin installed

Hope we can fix this issue

**Comment by valiquette** [comment]
it looks like the bridge section which should be set by homebridge may have been edited. I am only guessing because the username which is a MAC address would probably start with E0 and the port is not in the expected range.
Try
deleting this line and save the config
"_bridge": {
"username": "12:34:5G:6B:78",
"port": 12345
},
You should be able to add it to homekit then. 
if you want to run it as child bridge, set that option from the plugin screen "wrench" icon 
https://github.com/homebridge/homebridge/wiki/Child-Bridges
