### ISSUE TITLE
Separating zones on WT25G2-0001

### ISSUE THREAD

**Issue by ocifersven** [valiquette/homebridge-orbit-irrigation#37]
First of all, **thank you** for making a much better plugin for Orbit B-hyve on Homebridge systems over the supposed "certified" version.

Everything in my B-hyve ecosystem is showing up in my Apple Home app without issue, all switchable with all things Apple. I'm running a single WT25G2-0001, plus 3x HT25-0000 w/ a BH1-0000 WiFi hub connecting them to my network. All the logs show zero issues after setup.

However, I'm trying to separate the Home app tiles for my WT25G2 sprinkler zones through the Home app itself. Inside the tile, I have 3x sprinkler zones with corresponding switches. When I tap the "Show as Separate Tiles" button, the 3x sprinkler zone switches remain in place under the 1x tile, but it then breaks out "Run All," "Smart Watering," and "System" as new tiles which weren't visible anywhere prior. 

As you'd probably gathered by now, I'm trying to break out the individual sprinklers, as one of those sprinkler zones doesn't belong in my _room_ labeled "Front Yard." Yet, no matter what I try, they continue to be grouped as 3x individual switches inside the 1x tile.

Is there something I've overlooked in .json configuration file, or is this an impenetrable Apple HomeKit limitation?

**Comment by ocifersven** [comment]
I should also mention that yes, I've been toggling on and off a few options such as "All zones" which became grouped with the sprinkler zones. But all the same, even with those options disabled, the sprinkler zones remain grouped under 1x tile.

**Comment by valiquette** [comment]
What you are asking for is a feature from the start, granted not verified in a while but it should work. I can't test this for myself right now. You can check out the readme for https://github.com/valiquette/homebridge-rachio-irrigation/blob/main/README.md 
I did not produce a readme like this for this plugin because I did not have a multi zone controller at the time for the screen shots, but I assume this is what you're looking for.

In the plugin you do need to un check the setting for "display as irrigation system", then in HomeKit you can show as separate tiles.
I have seen HomeKit not want to update the accessory change so you may want to try and remove the bridge for the Plugin assuming it is a child bridge, make the plugin change and re add it to HomeKit.

If this does not help let me know and I take a good look next week.

**Comment by ocifersven** [comment]
Well @valiquette, that did the trick. 

To recap, I removed the Orbit bridge from _inside_ the Apple Home App. Then, while navigating my Hoobs system (Homebridge), I made the changes to the plugin you suggested, **saved**, then re-added the (child) bridge by adding a new accessory inside the Apple "Home" app. From there ...Pandora's box. The setup options almost felt endless, leaving me both super overjoyed and maybe a touch overwhelmed through my own doing.

Through your walkthrough, I got exactly what I asked for along with some extra helpings of 'woah'. Now there just might be _too_ many switches. ;-)

Thank you so much for your help!
