### ISSUE TITLE
Plugin goes unresponsive after a couple days

### ISSUE THREAD

**Issue by tylerdorazio** [valiquette/homebridge-orbit-irrigation#58]
Hi there -

I absolutely love this plugin. It works incredibly well with Homebridge/HomeKit, but I’ve found that it loses connection with the orbit servers after some time of inactivity. 

Usually after a day or two, I need to restart the homebridge service to get updated status in HomeKit. 

Is there any keep alive or retry logic built in? Not sure if it’s using web sockets, etc?

particularly, I have built some automation around detection of when the sprinklers turn on (even from the b-hyve app). Those automations stop working after a day or two until restart.

**Comment by valiquette** [comment]
Thanks.
The updates are using a web socket connection which should auto reconnect. It will timeout in 30sec but the plugin send a ping on random interval between 20-25 sec which is set on start. My instance is not updating right now either. I take a look at this..

**Comment by valiquette** [comment]
The connection can be interrupted all day long and auto reconnect, but it there is an error the connection would close. Unfortunately the ping used to keep the connection open would cause an error and hence close the connection.
Thanks for pointing this out, my network must be stable enough that I never noticed. 

Fixed with a little better logging in the latest release.
